image: archlinux
packages:
- wrangler
environment:
  site: liskvork.org
  cloudflare_project: liskvork-org
  repo: liskvork.org
secrets:
  - 1de91367-132e-4d0b-865a-3b4fc621f8f1
  - 38d06266-17a7-4fde-a067-3172d4afb2f7
tasks:
- publish: |
    set +x
    export CLOUDFLARE_ACCOUNT_ID=`cat ~/.clouflare-account-id`
    export CLOUDFLARE_API_TOKEN=`cat ~/.cloudflare-page-api-token`

    wrangler pages deploy $repo/$site --project-name=$cloudflare_project

    unset CLOUDFLARE_ACCOUNT_ID
    unset CLOUDFLARE_API_TOKEN
    set -x
